### PR TITLE
Fix CI unit tests and improve linting

### LINKED ISSUE #112: Fix CI checks that fail silently
`unit-tests` and `make lint` are both failing silently on CI.

### PR DESCRIPTION
**Pull request by eelanagaraj**
Closes #112 

This fixes the issue of unit tests failing silently on CircleCI and on not being warned about mismatching `golangci-lint` versions being used on CI vs. locally. Test summaries for the unit tests now also show up properly on CircleCI.

# Problem
- Unit tests were failing because there was an issue with the `make ci-test` command. The command itself was completing successfully, even if tests within it failed. I think this is because the command `trap ... EXIT` doesn't work properly within a Makefile command. Moving the command directly into the `circleci` config fixes this problem.
- Linting looked like it was failing silently on CI. This was because the version running on CI is likely different than a locally installed version. While a more robust way of fixing this would be going towards the `celo-blockchain` solution, for now the current fix at least checks that the local linter being run is consistent with the CI linting run.

# Testing
- Checked to make sure that a failure within the unit tests now propagates through to CI failure
- Checked that the proper linter (specified in the var `GOLANGCI_VERSION`) runs on CI, and that the local CI version matches this when running `make lint`

### CODE REVIEW

File: analyzer/operations.go [hunk 1]
```diff
@@ -410,6 +410,7 @@ func ReconcileLogOpsWithTransfers(logOps, transferOps []Operation, tobinTax *Tob
 	for index := range logOps {
 		logOp := logOps[index]
 		if logOp.Type.requiresTransfer() {
+			//nolint:gosec
```
Comment (yorhodes) [inline analyzer/operations.go:413]: I have no clue what's going on with this one tbh
we should investigate in future

File: Makefile [hunk 2]
```diff
@@ -38,9 +40,15 @@ test-cover:
...
 	go fmt ./...
 
+install-lint:
+	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$(GOLANGCI_VERSION)
+
 lint: ## Run linters.
 ifeq ("$(GOLANGCI_exists)","")
 	$(error "No golangci in PATH, consult https://github.com/golangci/golangci-lint#install")
+else ifneq ($(GOLANGCI_v_installed), $(GOLANGCI_VERSION))
+	$(error "Installed golangci version $(GOLANGCI_v_installed) \
```
Comment (yorhodes) [inline Makefile:50]: 🙏

File: Makefile [hunk 3]
```diff
@@ -38,9 +40,15 @@ test-cover:
 fmt: 
 	go fmt ./...
 
+install-lint:
+	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v$(GOLANGCI_VERSION)
```
Comment (yorhodes) [inline Makefile:44]: will everyone have `sh` ?

File: .golangci.yml [hunk 4]
```diff
@@ -10,7 +10,7 @@ run:
 linters:
   disable-all: true
   enable:
-    # - deadcode
+    - deadcode
```
Comment (yorhodes) [inline .golangci.yml:13]: 🚀

**Review by yorhodes — APPROVED** [review]
Thanks for fixing!
🙇‍♂️ incremental progress

**Comment by yorhodes** [comment]
I think if you include the "fixes/closes #112" in the PR description, it will close automatically on merge

File: analyzer/operations.go (hunk 1 above)
Comment (eelanagaraj) [reply analyzer/operations.go:413]: yeah, thanks for pointing out actually also a merge conflict that was silently resolved weirdly, fixing now (no longer need the nolint) -- a bit of a tricky loop though as `logOp` gets modified but in such a way that I think a shallow copy suffices. Def wanna understand this better though

File: Makefile (hunk 3 above)
Comment (eelanagaraj) [reply Makefile:44]: just for CI--changed the name so that's clear!
