### PR TITLE
Fix error logging to not modify underlying object

### LINKED ISSUE #155: Rosetta CLI checks fail to initialize when running the second time
Need to kill Rosetta node in between running `rosetta-cli check:...` otherwise receive:
```
Command Failed: error details populated in /network/options: /network/options: /network/options not attempting retry: unable to initialize asserter
```

Hypothesis: this happens only after the Rosetta node receives a `CeloClientError`, usually caused when the `rosetta-cli` is killed with `Ctrl-c`. It may have to do with the context being cancelled :
```
ERROR CeloClientError  srv=rpc  endpoint=TraceTransaction err="can't run celo-rpc tx-tracer: context canceled"
```
Unclear if this is a bug in `rosetta` or in the `rosetta-cli` checks. Not a high-priority bug, but use this issue to collect information/hypotheses about this issue.

### PR DESCRIPTION
**Pull request by eelanagaraj**
# Description
CLI checks were failing because details were being populated in `network/options` (if an error had been logged at some point). Reason: we were modifying the `Err*` vars and then logging the details, fix here is to create a copy of the error + modify+log this copy.

Incidentally seems to fix #155 as well.

# Testing
- Adds a unit test for the `LogErrDetails` function
- Fixes asserter error when restarting CLI

### CODE REVIEW

File: service/rpc/errors.go [hunk 1]
```diff
@@ -61,10 +61,12 @@ func LogErrUnimplemented(rosettaEndpoint string) *types.Error {
 }
 
 func LogErrDetails(rosettaErr *types.Error, err error) *types.Error {
-	rosettaErr.Details = map[string]interface{}{
+	copyErr := &types.Error{}
+	*copyErr = *rosettaErr
```
Comment (yorhodes) [inline service/rpc/errors.go:65]: this syntax scared me but I googled and apparently this is standard go practice 🤷‍♂️

**Review by yorhodes — APPROVED** [review]

File: service/rpc/errors.go (hunk 1 above)
Comment (eelanagaraj) [reply service/rpc/errors.go:65]: I feel that 😂 was surprised myself when googling lol
